version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: templogs
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
     - homeAssistantDB:/var/lib/mysql
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdbStorage:/var/lib/influxdb2:rw
    env_file:
      - ./influxdb/.env
    entrypoint: ["./influxdb/entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - homeAssistantCache:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  homeAssistantDB: {}
  influxdbStorage: {}
  homeAssistantCache: {}