version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: templogs
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
     - homeAssistantDB:/var/lib/mysql
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdbStorage:/var/lib/influxdb2:rw
    env_file:
      - ./influxdb/.env
    entrypoint: ["./influxdb/entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

volumes:
  homeAssistantDB: {}
  influxdbStorage: {}